site_name: Pop Description

markdown_extensions:
    - toc:
        baselevel: 2

theme:
    name: readthedocs
    custom_dir: theme/
        
extra_css: 
    - extra.css
    
nav:
    - Home: index.md
    - Pop : pop.md
    - Pop.AI : pop.ai.md
    
highlightjs: true
hljs_languages: [python, cpp, java, javascript]

static_templates:
    - 404.html

include_search_page: true
search_index_only: false

include_homepage_in_sidebar: true
prev_next_buttons_location: bottom
navigation_depth: 4
titles_only: false
sticky_navigation: true
collapse_navigation: true
