site_name: Pop Description

markdown_extensions:
    - toc:
        baselevel: 2

theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - python
        - cpp
        - java
        - javascript
        
extra_css: 
    - extra.css
    
nav:
    - Home: index.md
    - Pop : pop.md
    - Pop.AI : pop.ai.md
