site_name: Pop Description

markdown_extensions:
    - toc:
        baselevel: 2

theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - python
    #custom_dir: 'custom_theme'
 
markdown_extensions:
    - toc:
        permalink: true
 
extra_css: 
    - extra.css
    
nav:
    - Home: index.md
    - Pop : pop.md
    - Pop.AI : pop.ai.md
    - Pop.CAN : pop.can.md
    - Pop.Dataset : pop.dataset.md
    - Pop.Pilot : pop.pilot.md
    - Pop.Util : pop.util.md
    
highlightjs: true
hljs_languages: [python, cpp, java, javascript]
