site_name: Pop Description

markdown_extensions:
    - toc:
        baselevel: 3
        permalink: true

theme:
    name: 'rtd-dropdown'
    highlightjs: true
    hljs_languages:
        - python
   custom_dir: custom_theme/
        
extra_css: 
    - extra.css
    
nav:
    - Home: index.md
    - Pop : pop.md
    - Pop.AI : pop.ai.md
    - Pop.Pilot : pop.pilot.md
    - Pop.CAN : pop.can.md
    
highlightjs: true
hljs_languages: [python, cpp, java, javascript]
