site_name: Pop Description
theme: flatly
highlightjs: true
markdown_extensions:
    - toc:
        baselevel: 2
        
extra_css: 
    - extra.css
    
nav:
    - Home: index.md
    - Pop : pop.md
    - Pop.AI : pop.ai.md
